SET VB_PATH=C:\Program Files (x86)\Microsoft Visual Studio\VB98
SET ACCPAC_DEV_HOME=C:\CC
call setproj.bat
set LIB=%PLUSWDEV%\LIB;%XERCES_C_HOME%\lib;%LIB%
set INCLUDE=%PLUSWDEV%\INCLUDE;%PLUS_ICONS%;%PLUS_BITMAPS%;%XERCES_C_HOME%\INCLUDE;%INCLUDE%
path %PLUS_BIN%;%PATH%
